services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: wilson
      POSTGRES_PASSWORD: wilson
      POSTGRES_DB: wilson
    ports:
      - '5432:5432'
    volumes:
      - wilson_pg:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U wilson -d wilson']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  nats:
    image: nats:2.10-alpine
    command: ['-js', '-m', '8222']
    ports:
      - '4222:4222'
      - '8222:8222'

volumes:
  wilson_pg:
